#!/bin/bash

export gpTest cTestCurDir gpTestList gpCmdName gpSaveTestEnv
gpCmdName=manual-test-RemoteSelect

# -------------------
# Set current directory location in PWD and cTestCurDir
if [ -z "$PWD" ]; then
    PWD=$(pwd)
fi
cTestCurDir=$PWD

# -------------------
# Define the location of this script
gpTest=${0%/*}
if [ "$gpTest" = "." ]; then
    gpTest=$PWD
fi
cd $gpTest >/dev/null 2>&1
gpTest=$PWD
cd - >/dev/null 2>&1

gpBin=$gpTest/../git-core
cd $gpBin >/dev/null 2>&1
gpBin=$PWD
cd - >/dev/null 2>&1

. $gpTest/test.inc
fTestSetupEnv
fTestCreateEnv
cd $HOME >/dev/null 2>&1
tar -xzf $gpTest/test-env_ProjLocalDefined.tgz
cd - >/dev/null 2>&1

. $gpBin/gitproj-remote.inc

tPrompt="Select by number, the location for the remote git and raw files? "
fRemoteGetDirList $cDatMount3
tDirList=$gResponse
tHelp=$(
    cat <<EOF
This is a list of dirs under the -d pMountDir, if you gave that option.
And might lists other possible mounted directories to choose from.
EOF
)

gpAuto=0
#echo "cDatMount3=$cDatMount3"
#echo "tDirList=$tDirList"

gpProjName=example
gpLocalTopDir=$cDatHome/$cDatProj1

fRemoteGetMountDir $cDatMount3
tStatus=$?
echo
echo '======================='
echo "Selected: gResponse=$gResponse"
echo "Status=$tStatus"
