#!/bin/bash

echo "Test pre-commit to see how the hook works, so it can be made better."

# Mainly make sure files in ProjName/raw/ are not committed.  I.e. do
# not depend on .gitignore to prevent files in raw/ from being
# committed.  If a use wants to commit a large binary file, no
# problem, but they must put it outside of raw/ and use the -f option
# to overrided any ignore rules.

exit 1
