#!/bin/bash

# --------------------
fIsBinary()
{
    local pFile="$1"
    grep -Hm1 '^' <"$pFile" | grep -q '^Binary'
    # Copied from: https://unix.stackexchange.com/questions/275516/is-there-a-convenient-way-to-classify-files-as-binary-or-text
}

# ========================================
# Main

# ----------
if [ $# -eq 0 ]; then
    cat <<EOF
Usage:
    rm-trailing-sp FILE...
    
Remove trailing whitespace. Only use this on text files.
The script skip files when the "file" command does not show "ASCII text".

Backup the files if you want to be careful.
EOF
    exit 1
fi

# ----------
for tFile in $*; do
    if [ ! -f $tFile ]; then
        echo "Skipping non-file $tFile"
        continue
    fi

    if [ ! -w $tFile ]; then
        echo "Skipping non-writable $tFile"
        continue
    fi

    file $tFile | grep -q 'text'
    if [ $? -ne 0 ]; then
        echo "Skipping binary $tFile"
        continue
    fi

    if fIsBinary $tFile; then
        echo "Skipping binary $tFile"
        continue
    fi

    sed -Ei 's/[[:space:]]*$//' $tFile
done
