language: bash

env:
  - gpVerbose=3

script :
  - cd test; make .ran-test-pre-commit.tmp .ran-test-remote.tmp
#  - cd test; make test-all

before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - git
      - bash
      - coreutils
      - gawk
      - git-flow
      - libpod-markdown-perl
      - openssh-client
      - openssh-server
      - perl
      - rsync
      - sed
      - tidy

matrix:
  include:
#    - os: linux
#      dist: focal
    - os: linux
      dist: bionic
#    - os: linux
#      dist: xenial

branches:
  only:
    - develop
    - main
