language: bash

env:
  - gpVerbose=3

script :
  - cd test; make test-all
#  - cd test; make .ran-test-pre-commit.tmp .ran-test-remote.tmp

before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - git
      - bash
      - coreutils
      - gawk
      - git-flow
      - libpod-markdown-perl
      - openssh-client
      - openssh-server
      - perl
      - rsync
      - sed
      - tidy

# https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution
# https://travis-ci.community/t/free-oss-credits-usage-calculation/10832/5?u=turtleengr

os: linux
dist: bionic
arch:
     - arm64

#matrix:
#  include:
#    - os: linux
#      dist: focal
#    - os: linux
#      dist: bionic
#    - os: linux
#      dist: xenial

branches:
  only:
    - develop
    - main
