#!/bin/bash

#--------------------
fUsage()
{
	cat <<EOF
Usage:
	proj-new-local -n

Description
	Create a new git repo in this directory. After adding and
	committing files, use "proj-new-remote" to push the repo to a
	mounted drive.
	
Dependencies
	packages: git, git-flow 
EOF
	exit 1
}

# --------------------
fCheckForPkg()
{
	local pPkg=$1

	if ! (dpkg -l $pPkg 2>/dev/null | grep -q "^ii *$pPkg"); then
		echo "Error: Missing package: $pPkg"
		exit 1
	fi
}

# --------------------
fCheckForGit()
{
	if git $cOrigin; then
		echo "Error: .git already exists for the directory."
		git branch
		exit 1
	fi
}

# --------------------
fCreateGitDir()
{
	cat <<EOF >.gitignore
*.tmp
*~
.cache/
.cvsignore
CVS/
core
nohup.out
proxy/
thumbs/
tmp/
EOF
	set -x
	git init
	git flow init
	git checkout develop
	git add .gitignore
	git status
	set +x
}

# ====================
# Main

if [ $# -eq 0 ]; then
	fUsage
fi

export cOrigin='config --get remote.origin.url'

fCheckForPkg git
fCheckForPkg git-flow
fCheckForGit
fCreateGitDir

exit 0
