#!/bin/bash

#--------------------
fUsage()
{
    exit 1
    cat <<\EOF >/dev/null
=pod

=for text ========================================

=for html <hr/>

=head1 NAME git proj status

=head1 SYNOPSIS

 git proj status [-v]

=head1 DESCRIPTION

    Verify gitproj.config.remote-raw-dir is defined
    Verify origin is set to a path that exists (if mounted)
    Verify gitproj.config.remote-raw-dir exists (if mounted)
    Give a "diff" (-qr) of the raw files, local vs remote (if mounted)
    Do a "git status"

Check install related health

    fComGetVer
    Compare .git/hooks/pre-commit to $gpDoc/hooks/pre-commit
    if -v, show all the proj related config settings.

=cut

EOF
}
