#!/bin/bash

cat <<EOF
git proj rm pFile...
git proj rm -e
EOF

for tFile in $*; do
    if [ -d $tFile ]; then
        echo error
    fi
    if [ -l $tFile ]; then
        rename -s $tFile $tFile.trash
        rm $tFile
    fi
done

# Remove trash files and empty dirs
tPrompt="-i"
cd raw
find * -type f -name '*.trash' -exec rm $tPrompt {} \;
find * -type d -empty -delete
