#!/bin/bash

export gpBin gpCmdName tSrc

#--------------------
fUsage()
{
    # Quick help, run this:
    # git-proj-pull -h | less

    local pStyle="${1:-usage}"

    fComUsage -s $pStyle -f $gpBin/$gpCmdName
    exit 1

    cat <<EOF >/dev/null
=pod

=for text ========================================

=for html <hr/>

=head1 NAME git proj pull

=head1 SYNOPSIS

    git proj pull [-g] [-d] [-a] [-y|-n] [common-options]

=head1 DESCRIPTION

rsync will be used top copy the [remote-raw-origin]/[ProjName].raw/ files
to '[ProjName]/raw/'.

If the -g option is given then run:

 "git pull origin [current-branch]"

=head1 OPTIONS

=over 4

=item B<-g>

If the -g option is given then run:

 "git push origin [current-branch]"

=item B<-d>

If the -d option is used, then the local raw/ will be made identical
to the remote raw/. I.e. files might be deleated from the local raw/.

See the help EXAMPLES section, in "git proj push", for a "save" way to
use this option.

=item B<-a>

This turns on automated push for raw/ files. Use the -y or -n to
select the action. -n will just display what would be done.

If there is a -d option, that will be removed and the -n option
will be added. -d could be very distructive, so it needs to be
run interactively.

=item B<-y|-n>

If -y, then pull files from the remote raw/

If -n, then just show what would be pulled from the remote raw/

=item B<[common-options]>

 -h
 -H usage|text|html|md|man|int|int-html|int-md
 -q, -v, -V N     (gpVerbose)
 -x, -xx..., -X N (gpDebug)

Run "git proj -h" for details.

=back

=head1 RETURN VALUE

 0 - if OK
 !0 - if errors

=for comment =head1 ERRORS

=for comment =head1 EXAMPLES

=for comment=head1 ENVIRONMENT

=for comment=head1 FILES

=head1 SEE ALSO

 git proj
 git proj init
 git proj remote
 git proj clone
 git proj add
 git proj push
 git proj pull
 git proj config
 git proj status
 git flow

=for comment =head1 NOTES

=for comment =head1 CAVEATS

=for comment =head1 DIAGNOSTICS

=for comment =head1 BUGS

=for comment =head1 RESTRICTIONS

=head1 AUTHOR

TurtleEngr

=head1 HISTORY

GPLv3 Copyright 2021 by TurtleEngr

=cut

EOF
} # fUsage

# ========================================
# Main

gpCmdName=${BASH_SOURCE##*/}
tSrc=${BASH_SOURCE##*/}

# -------------------
# Set current directory location in PWD
if [ -z "$PWD" ]; then
    PWD=$(pwd)
fi

# -------------------
# Define the location of this script
gpBin=${0%/*}
if [ "$gpBin" = "." ]; then
    gpBin=$PWD
fi
cd $gpBin >/dev/null 2>&1
gpBin=$PWD
cd - >/dev/null 2>&1

# -------------------
. $gpBin/gitproj-com.inc
# Calls: fComSetGlobals

. $gpBin/gitproj-pull.inc
fComGetProjGlobals

tSrc=${BASH_SOURCE##*/}
pBranchFlag=0
pDeleteRaw=0
gpYesNo=""
gpAuto=0
while getopts :adgbnyhH:qvV:xX: tArg; do
    case $tArg in
        # Script arguments
        a) gpAuto=1 ;;
        d) pDeleteRaw=1 ;;
        g) pBranchFlag=1 ;;
        n) gpYesNo=No ;;
        y) gpYesNo=Yes ;;
        # Common arguments
        h) fUsage long ;;
        H) fUsage "$OPTARG" ;;
        q) gpVerbose=0 ;;
        v) gpVerbose=2 ;;
        V) gpVerbose=$OPTARG ;;
        x) let ++gpDebug ;;
        X) gpDebug=$OPTARG ;;
        # Problem arguments
        :) fError -m "Value required for option: -$OPTARG" -l $tSrc:$LINENO ;;
        \?) fError -m "Unknown option: $OPTARG" -l $tSrc:$LINENO ;;
    esac
done
shift $((OPTIND - 1))
if [ $# -ne 0 ]; then
    fError -m "Unknown option: $*" -l $tSrc:$LINENO
fi
if [[ ${gpAuto:-0} -ne 0 && $pDeleteRaw -ne 0 ]]; then
    pDeleteRaw=0
    gpYesNo=No
    fLog -f -p warning -m "-d cannot be used with -a. Removing -d option and adding -n option." -l $tSrc:$LINENO
fi

# ----------
fPullFromOrigin $pBranchFlag $pDeleteRaw
exit 0
