#!/bin/bash

cat <<EOF
git proj mv pOldFile pNewFile
git proj mv pOldFile pNewDir
git proj mv pOldDir pNewDir
    if there are symlinks in pOldDir, they need to be moved too
EOF

if [ -f pFileOld ]; then
    if [ -l $pFileOld ]; then
        rename -s $pFileOld $pFileNew
    fi
    mv $pFileOld $pFileNew
fi

if [ -d pFileOld ]; then
    echo "TBD"
fi
