#!/bin/bash

#--------------------
fUsage()
{
    # Quick help, run this:
    # git-proj-config -h | less
    local pStyle="${1:-usage}"

    fComUsage -s $pStyle -f $gpBin/$gpCmdName
    exit 1
    cat <<\EOF >/dev/null
=pod

=for text ========================================

=for html <hr/>

=head1 NAME git proj config

=head1 SYNOPSIS

    NOT IMPLEMENTED YET
    git proj config [common-options]

=head1 DESCRIPTION

This is a text menu driven tool for checking and tuning up your
git-proj configurations. There are 4 configuration "levels" to
consider: Product, User, Project, and Local. The standard git support
configs at the User and Local levels, and the usual --global and
--local options can be used with "git config" to get and set
variables. Or you can edit the files directly. See the FILES section
for files listed by their levels.

The "git proj config" tool has two major sections: "Health Checks" and
"Actions".

The "problem" health check will report serious problems that should be
fixed (some fix-up help will be offered). The other health checks are
useful for finding areas that you might want to update.  For example,
in your user level configs may have changed and you might notice some
project level configs are different. You can then run and "action" to
make them consistent.

The "actions" are used to copy config variables and files between the
different "levels". Some actions will only copy things that are
missing, while other actions can "force" changes.

=head2 Config Files

       ProductConfig	/usr/share/doc/git-proj/config/gitconfig
       UserConfig 	~/.gitconfig (--global)
       ProjectConfig 	PROJ/.gitproj
       LocalConfig 	PROJ/.git/config (--local)

       ProductIgnore 	/usr/share/doc/git-proj/config/gitignore
       UserIgnore    	~/.gitignore
       ProjectIgnore 	PROJ/.gitignore

       ProductPreCommit	/usr/share/doc/git-proj/hooks/pre-commit
       UserPreCommit	~/.pre-commit
       ProjectPreCommit PROJ/.pre-commit
       LocalPreCommit	PROJ/.git/hooks/pre-commit

=head2 Main Menu Options

=over 4

=item (1) Quit, exit git-proj-config

In the lower level menus, #1 will change to "Back" and "Quit" will move
to #3.

=item (2) Help

This will be available in all menus.

=item (3) Run health checks that look for problems [errors]

=item (4) Run health checks that look for differences [diff, warnings]

=item (5) Run all health checks and report their status [info]

=item (6) Select actions to update configs or files

=back

=head2 Global User Level Health Checks

These are done even if not in a git-proj managed workspace.

The Validate Checks, check ProductConfig and --global.

=over 4

=item * Validate "facility" name [error]

=item * Validate "bin" and "doc" locations [error]

=item * Validate all bool vars are only true/false [error]

=item * Validate all int vars only have numbers [error]

=item * Compare --global with ProductConfig [diff]

=item * Compare UserIgnore with ProductIgnore [diff]

=item * Compare UserPreCommit with ProductPreCommit [diff]

=item * if git-flow=true

=over 4

=item * is git-flow installed? [warning]

=item * are git-flow section vars defined in --global? [warning]

=back

=back

=head2 Local and Project Level Health Checks

These are only done if you are in a git-proj managed workspace.

The Validate Checks, check ProjectConfig and --local.

=over 4

=item * If defined, validate "facility" name [error]

=item * If defined, validate "bin" and "doc" locations [error]

=item * Validate all gitproj bool vars are only true/false [error]

=item * Validate all gitproj int vars only have numbers [error]

=item * Compare ProjectConfig with --global (only list the diffs from
all gitproj sections and the diffs that are in .gitproj and also in
--global [diff]

=item * Compare ProjectConfig with --local (only list the diffs from
all gitproj sections and the diffs that are in ProjectConfig and also
in --global [diff]

=item * Compare ProjectIgnore with UserIgnore [diff]

=item * Compare ProjectPreCommit with UserPreCommit [diff]

=item * Compare LocalPreCommit with ProjectPreCommit [diff]

=item * Note the disabled pre-commit checks [info]

=item * gitproj.config.proj-name != the git top dir name [warning]

=item * gitproj.config.local-status - is TBD [error]

=item * remote.origin.url - is not defined [warning]

"git proj init" needs to be run.

=item * gitproj.config.remote-status - is TBD [error]

"git proj remote" needs to be run.

=item * gitproj.config.remote-raw-origin - is TBD [warning]

"git proj remote" needs to be run.

=item * warn if gitproj.config.remote.min-space is < 2x existing space [warning]

=item * if gitproj.config.remote-raw-origin, report if not found. [warning]

Suggest mounting it or running "git proj remote".

=back

=head2 Additional Checks

=over 4

=item * List symlinks with problems [error]

=item * Report on all symlinks in PROJ [info]

=item * Check for big binary files, not in raw/ [warning]

=back

=head2 Run all health checks and report their status [info]

This will list all of the current config var settings and what file
they are set in. Other statistics about the course will also be
listed, for example, the number of files in raw/ and the space they
use.

=head3 Select actions to update configs or files

Define the config sections or files that you want to update or copy."

=over 4

=item (1) Back

=item (2) Help

=item (3) Quit, back to main

=item (4) Copy all config section: core, alias, git-flow, gitproj.config

=item (5) Copy some config section: git-flow, gitproj.config

=item (6) Only copy gitproj.config section

=item (7) Only copy gitproj.hooks section

=item (8) Copy gitignore file

=item (9) Copy pre-commit file

=item Select the configs or file to be moved:

=back

=head2 Config File Level Direction

These options are for all of the config files actions.

Define what level to copy from and what level to copy to.

For example, if you select 'Product -> User', then that means sections
from /usr/share/doc/git-proj/config/gitconfig will be copied to
~/.gitconfig

The config 'levels' and files are more completely described in the
user-doc 'gitproj Configuration Documentation' (config.md

=over 4

=item (4) Product -> Use

=item (5) User -> Project

=item (6) Project -> Local

=item (7) Local -> Project

=item (8) Project -> User

=item Select the from/to:

=back

=head2 Only copy missing or Force

If you select 'Force copy', then the variables in the 'from' file will
replace the variables in the 'to' file.

If you select 'Only copy missing', then existing variables, in the
'to' file, will not be replaced with variables in the 'from' file. But
missing variables will be copied from the 'from' file.

=over 4

=item (4) Force copy

=item (5) Only copy missing
    
=item Select the "force" option:

=back

=head2 Copy gitignore file

Define what level to copy from and what level to copy to.

For example, if you select 'Product -> User', then that means
/usr/share/doc/git-proj/config/gitignore will be merged to
~/.gitignore

An existing ~/.gitignore will be copied to ~/.gitignore.bak The
updated ~/.gitignore will be sorted with duplicates and comments
removed.

The config 'levels' and files are more completely described in the
user-doc 'gitproj Configuration Documentation' (config.md)

=over 4

=item (4) Product -> User

=item (5) User -> Project

=item (6) Project -> User

=item Select the from/to:

=back

=head2 Copy pre-commit file

Define what level to copy from and what level to copy to.

For example, if you select 'Product -> User', then that means
/usr/share/doc/git-proj/hooks/pre-commit will be copied to
~/.pre-commit

An existing ~/.pre-commit will be copied to ~/.pre-commit.~1~

The config 'levels' and files are more completely described in the user-doc
'gitproj Configuration Documentation' (config.md)

=over 4

=item (4) Product -> Use

=item (5) User -> Project

=item (6) Project -> Local

=item (7) Local -> Project

=item (8) Project -> User

=item Select the from/to:

=back

=head2 Continue?

Selecting 'Yes' will make the changes you have selected. If you do not
want to continue, then you can Quit, to return to the main menu, or
select the Back options to update your selections.

=over 4

=item (1) Back

=item (2) Help

=item (3) Quit, back to main

=item (4) Yes, continue

Are the above actions correct?

=back

=head1 OPTIONS

=over 4

=item B<[common-options]>

 -h
 -H usage|text|html|md|man|int|int-html|int-md
 -q, -v, -V N     (gpVerbose)
 -x, -xx..., -X N (gpDebug)

Run "git proj -h" for details. Or "man git-proj" for help with all the
sub-commands.

=back

=head1 RETURN VALUE

 0 - if OK
 !0 - if errors

=for comment =head1 ERRORS

=for comment =head1 EXAMPLES

=for comment=head1 ENVIRONMENT

=head1 FILES

=head2 Product Level

=over 4

=item * ProductConfig is short for /usr/share/doc/git-proj/config/gitconfig

=item * ProductIgnore is short for /usr/share/doc/git-proj/config/gitignore

=item * ProductPreCommit is short for /usr/share/doc/git-proj/hooks/pre-commit

=back

=head2 User Level

=over 4

=item * --global is short for ~/.gitconfig

=item * UserIgnore is short for ~/.gitignore

=item * UserPreCommit is short for  ~/.pre-commit

(Note: this may change to: ~/.git/hooks/pre-commit)

=back

=head2 Project Level

=over 4

=item * ProjectConfig is short for ProjName/.gitproj

=item * ProjectIgnore is short for ProjName/.gitignore

=item * ProjectPreCommit is short for ProjName/.pre-commit

=back

=head2 Local Level

=over 4

=item * --local is short for ProjName/.git/config

=item * LocalPreCommit is short for ProjName/.git/hooks/pre-commit

=back

=head1 SEE ALSO

 git proj
 git proj remote
 git proj clone
 git proj push
 git proj pull
 git proj set
 git proj status
 git proj add   TODO
 git proj config
 git flow

=head1 NOTES

The checks and actions do not cover "all" of the configuration changes
that you might like. "git proj config" is just a helper tool to point
out problems and differences that might matter.

You are free to edit the files directly. Just make sure the bool and
int vars are syntactically OK. Also the Product level configs should
probably be left unchanged, so that git-proj updates will not
overwrite your changes. Put the changes you want to keep at the
--global or Project Levels.

=for comment =head1 CAVEATS

=for comment =head1 DIAGNOSTICS

=for comment =head1 BUGS

=for comment =head1 RESTRICTIONS

=head1 AUTHOR

TurtleEngr

=head1 HISTORY

GPLv3 Copyright 2021 by TurtleEngr

=cut

EOF
    exit 1
}

# ====================
# Main

export gpBin gpCmdName tSrc

gpCmdName=${BASH_SOURCE##*/}
tSrc=${BASH_SOURCE##*/}

# -------------------
# Set current directory location in PWD
if [ -z "$PWD" ]; then
    PWD=$(pwd)
fi

# -------------------
# Define the location of this script
gpBin=${0%/*}
if [ "$gpBin" = "." ]; then
    gpBin=$PWD
fi
cd $gpBin >/dev/null 2>&1
gpBin=$PWD
cd - >/dev/null 2>&1

# -------------------
. $gpBin/gitproj-com.inc
# Calls: fComSetGlobals
. $gpBin/gitproj-config.inc

# -------------------
while getopts :hH:qvV:xX: tArg; do
    case $tArg in
        # Script arguments
        # Common arguments
        h) fUsage long ;;
        H) fUsage "$OPTARG" ;;
        q) gpVerbose=0 ;;
        v) gpVerbose=2 ;;
        V) gpVerbose=$OPTARG" ;;
        x) let ++gpDebug ;;
        X) gpDebug=$OPTARG" ;;
        # Problem arguments
        :) fError -m "Value required for option: -$OPTARG" -l $tSrc:$LINENO ;;
        \?) fError -m "Unknown option: $OPTARG" -l $tSrc:$LINENO ;;
    esac
done
shift $((OPTIND - 1))
if [ $# -ne 0 ]; then
    fError -m "Unknown option: $*" -l $tSrc:$LINENO
fi

# ----------
fConfigMenu
exit 0
