#!/bin/bash

export gpCmdName gpBin cCurDir

#--------------------
fUsage()
{
    # Quick help, run this:
    # git-proj-init -h | less

    local pStyle="${1:-usage}"

    fComUsage -s $pStyle -f $gpBin/$gpCmdName
    exit 1

    cat <<\EOF >/dev/null
=pod

=for text ========================================

=for html <hr/>

=head1 NAME git proj init

=head1 SYNOPSIS

    git proj init local [-a]
    	     	  	[-l pLocalDir]
    	     	  	[-r pLocalRawDirPat]
			[-k pSymLink] [-s pMaxSize] [-m] [-f] [-h]

        Defaults: [-l $PWD] [-r ../[NAME].raw] [-k raw] [-s 10K] [-m] [-f]

    git proj init remote [-a] -d pMountDir [-r pRawRemoteDir ]
    	     	  	 [-s pMinSpace] [-h]

        Defaults: [-r pMountDir/NAME.raw]

=head1 DESCRIPTION

=head2 git proj init local

This will create a local git repo with branches. If git-flow is
installed can will optionally be setup too. After this setup
the remove git repo with "git proj init remote"

If there is a -a option, "git proj init local" will be run with all
the default options, which can be overridden with the options.

If there is no -a option, you will be prompted for the settings.  See
the OPTION section for details.

When the local and remove git repos are setup, all the setings
will be saved to ~/.gitproj.config and
[project]/gitproj/config.$HOSTNAME. Includes are put in ~/.gitconfig
and [project].git/config to point to the gitproj config files.

=head2 git proj init remote

This will create a remote git repo on an external drive.

(Future versions may support repos on remove computers, where you have
rsync access.)

=head1 OPTIONS  git proj init local

=over 4

=item B<-a>

The -a option will automattically run the whole init process with
default settings. The options can be defined to override the default
settings.

=item B<-l pLocalDir>

Define the existing project directory. The last directory will be used
for the name of the project. Default: current directory

    Dir (-l) [$PWD]? $gpLocalTopDir
        So the project Name will be: ${gpLocalTopDir##*/}

=item B<-r pLocalRawDirPat>

Set the location for large binary files. It cannot be *in* any of the
project directories. It will be created, if it does not existi. The
path must be relative to the project dir (and not too far away or
cloning the project may not work). The files in the raw directory will
NOT be versioned--only the latest copy will be saved. Default: ".."

    Raw dir (-r) [..]?
        The README.txt file will point to the raw dir.

=item B<-k pSymLink>

Define the symlink name that will point to the Raw dir. It will be
created in the project's top dir. If the Raw dir is moved, this link
will need to be updated. Symlink in the git directories will point to
this dir and the symlinks will be versioned. Default: raw

    Symlink (-k) [raw]?
        (update the README.txt)

=item B<-s pMaxSize>

Define the "size" for large binary files. Default 10K

    Size (-s) [10K]?

=item B<-m>

These binary files greater than [pSize]  were found in your project dir:

    [file list]

The listed files can be moved to the project's raw directory. Dirs
will be created in the raw directory that correspond to the project's
directory. A symlink will replace the moved file. The symlink will
point to [raw]

    Move the files (-m) [y/n]?

=item B<-f>

[If git-flow is installed]

    Setup git-flow (-f) [y/n]?

=item B<-h>

=back

=head1 OPTIONS  git proj init remote

=over 4

=item B<-d pMountDir>

Export the git repo to an external drive (or another local dir) This
is usually the removable drive's "top" directory.  Ideally the top
directory should be different across a set of external drives, so that the
local "origin" can be used to make sure the proper git repo is found
on the drive. "origin" will be set to $pMountDir/ProjName.git

After adding and committing files, run this script to copy this git
repo to a mounted drive (or to another local directory).

A mounted drive should have top directory that is different from other
drives so that the repo can be found with it's "origin" name.

For example, with a mount point: /mnt/usb-video create the remote git
at the top directory video-2019-04-01, with:

 git proj init -e /mnt/usb-video/video-2019-04-01

=item B<-r pRawRemoteDir>

        Default: [-r pMountDir/ProjName.raw]

=item B<-s pMinSpace>

This is the minium space that should be available on the external
drive.  The command will not continue if there is not enough space.
The available space must also be twice the size of the space used by
ProjName.raw.

Default: 20g

=item B<-h>

=back

=head1 RETURN VALUE

 0 - if OK
 !0 - if errors

=for comment =head1 ERRORS

=for comment =head1 EXAMPLES

=for comment=head1 ENVIRONMENT

=for comment=head1 FILES

=head1 SEE ALSO

 git proj
 git proj clone
 git proj add
 git proj push
 git proj pull
 git proj set
 git proj status
 git flow

=for comment =head1 NOTES

=for comment =head1 CAVEATS

=for comment =head1 DIAGNOSTICS

=for comment =head1 BUGS

=for comment =head1 RESTRICTIONS

=head1 AUTHOR

TurtleEngr

=head1 HISTORY

GPLv3 Copyright 2021 by TurtleEngr

=cut

EOF
    exit 1
} # fUsage

# ========================================
# Main

gpCmdName=${BASH_SOURCE##*/}
export tSrc=${BASH_SOURCE##*/}

# -------------------
# Set current directory location in PWD and cCurDir
if [ -z "$PWD" ]; then
    PWD=$(pwd)
fi
cCurDir=$PWD

# -------------------
# Define the location of this script
gpBin=${0%/*}
if [ "$gpBin" = "." ]; then
    gpBin=$PWD
fi
cd $gpBin
gpBin=$PWD
cd $cCurDir

# -------------------
. $gpBin/gitproj-com.inc
# Calls: fComSetGlobals

if [ $# -eq 0 ]; then
    fError -m "Missing options." -l $tSrc:$LINENO
fi

. $gpBin/gitproj-init.inc
# Calls: fInitSetGlobals

while getopts :al:r:k:s:mfhH:x tArg; do
    case $tArg in
        # Script arguments
        a) gpAuto=1 ;;
        l)
            gpLocalTopDir="$OPTARG"
            gpLocalRawDir=../${gpLocal##*/}
            ;;
        r)
            gpLocalRawDir="$OPTARG"
            gpRawRemoteDir="$OPTARG"
            ;;
        k) gpLocalRawSymLink="$OPTARG" ;;
        s) gpMaxSize=="$OPTARG"
	   gpRemoveMinSpace="$OPTARG"
	   ;;
        m) gpMove=1 ;;
        f) gpGitFlow=1 ;;
        # Common arguments
        h) fUsage long ;;
        H) fUsage "$OPTARG" ;;
        x) let ++gpDebug ;;
        # Problem arguments
        :) fError "Value required for option: -$OPTARG" $LINENO ;;
        \?) fError "Unknown option: $OPTARG" $LINENO ;;
    esac
done
shift $((OPTIND - 1))
if [ $# -ne 1 ]; then
    fError -m "local or remote needs to be specified." -l $tSrc:$LINENO
fi
case $1 in
    local) gpAction="fCreateLocalGit" ;;
    remote) gpAction="fCreateRemoteGit" ;;
    *) fError -m "Invalid option: $1. Expeced 'local' or 'remote'." -l $tSrc:$LINENO ;;
esac

$gpAction
exit 0
