#!/bin/bash

#--------------------
fUsage()
{
    exit 1

    cat <<EOF >/dev/null
=pod

=for text ========================================

=for html <hr/>

 git proj add pFilePath

    Copy pFilePath to [top_git_dir]/raw dir. The path will be
    duplicated (with "ln") in [top_git_dir]/raw dir and the file will
    remove and a symlink will be made to [top_git_dir]/raw dir
    location. Files can also be manually put in the "raw" symlink
    directory, then used from there directly or with symlinks to that
    directory. Do not link to, or reference files with the actual raw
    directory location, because the raw symlink could be changed to a
    new location.

    Note: the files do not need to be binary.

=cut

EOF
}
