ProdName=git-proj
ProdAlias=git-proj
ProdVer=0.5.2
ProdRC=
ProdBuild=1
ProdSupport=turtle.engr@gmail.com
ProdVendor=TurtleEngr / turtle.engr@gmail.com
ProdPackager=bruce
ProdCopyright=Copyright 2022. All rights reserved.
MkVer=2.2
ProdRelServer=moria.whyayh.com
ProdRelDir=/rel/released/software/own/git-proj/deb
ProdTag=tag-0-5-2-1
ProdOS=mx19
ProdOSDist=mx
ProdOSVer=19.4
ProdArch=x86_64
CurLogName = bruce
