name: package

# https://github.community/t/github-actions-trigger-workflow-on-succes-failure-of-other-workflow/16100/10?u=turtleengr

on:
  workflow_run:
    workflows: ["test"]
    branches: [develop]
    types:
      - completed

jobs:

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:

    - uses: actions/checkout@v2

    - name: InstallDeps
      run: cd test; make install-deps

    - name: Build
      run: cd package; make build

    - name: Package
      run: cd package; make package
