name: test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: cd test; make install-deps

    - name: Test
#      run: cd test; make test-all
      run: cd test; ./test-pull.sh
